spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      one:
        url: jdbc:mysql://192.168.100.102:3306/monitor_protocol
        username: root
        password: 123456
      two:
        url: jdbc:mysql://192.168.100.103:3306/monitor_protocol
        username: root
        password: 123456
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true